# Generated by Django 4.0.5 on 2024-03-04 18:00

from django.db import migrations


class Migration(migrations.Migration):
    from ..models import User
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(User.objects.create_user('root', '123'))
    ]
